# Basic settings
task: detect
mode: train

# Train settings
data: dataset/data.yaml # path to data file
epochs: 100 # number of epochs to train for
patience: 10 # early stop after N epochs without val improvement
imgsz: 640 # (int | list) train/val use int (square); predict/export may use [h,w]
save: True # save train checkpoints and predict results
save_period: 10 # save checkpoint every N epochs; disabled if < 1
# project parameter was commented out because we are using ARGS parameters
# project: results # (project name for results root
name: "result" # experiment name; results in 'project/name'

# Data augmentation settings
hsv_h: 0.015 # hue adjustment
hsv_s: 0.7 # saturation adjustment
hsv_v: 0.4 # brightness adjustment
scale: 0.5 # resizes images
